# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coco/MapReport.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'coco/MapReport.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63oco/MapReport.proto\x12\x04\x63oco\x1a\x1fgoogle/protobuf/timestamp.proto\"$\n\x08GeoPoint\x12\x0b\n\x03lat\x18\x01 \x01(\x02\x12\x0b\n\x03lng\x18\x02 \x01(\x02\"\xa0\x01\n\tMapReport\x12\x1d\n\x04type\x18\x01 \x01(\x0e\x32\x0f.coco.IssueType\x12\r\n\x05notes\x18\x02 \x01(\t\x12)\n\x11reported_location\x18\x03 \x01(\x0b\x32\x0e.coco.GeoPoint\x12\n\n\x02id\x18\x04 \x01(\t\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*\x84\x02\n\tIssueType\x12\x0f\n\x0bISSUE_OTHER\x10\x00\x12\x1b\n\x17ISSUE_ROUTE_OBSTRUCTION\x10\x01\x12\x18\n\x14ISSUE_INFRASTRUCTURE\x10\x02\x12\x0f\n\x0bISSUE_TRASH\x10\x03\x12\x19\n\x15ISSUE_UNSAFE_CROSSING\x10\x04\x12\x14\n\x10ISSUE_LONG_LIGHT\x10\x05\x12\x16\n\x12ISSUE_CONSTRUCTION\x10\x06\x12\x10\n\x0cISSUE_HAZARD\x10\x07\x12\x12\n\x0eISSUE_HOMELESS\x10\x08\x12\x15\n\x11ISSUE_NO_CURB_CUT\x10\t\x12\x18\n\x14ISSUE_MOVABLE_OBJECT\x10\nb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coco.MapReport_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ISSUETYPE']._serialized_start=265
  _globals['_ISSUETYPE']._serialized_end=525
  _globals['_GEOPOINT']._serialized_start=63
  _globals['_GEOPOINT']._serialized_end=99
  _globals['_MAPREPORT']._serialized_start=102
  _globals['_MAPREPORT']._serialized_end=262
# @@protoc_insertion_point(module_scope)
