apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-archiver
  namespace: foxglove
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::270582689972:role/data-archiver-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-archiver
  namespace: foxglove
spec:
  replicas: 64
  selector:
    matchLabels:
      app: data-archiver
  template:
    metadata:
      labels:
        app: data-archiver
        tags.datadoghq.com/service: data-archiver
        tags.datadoghq.com/env: dev
    spec:
      serviceAccountName: data-archiver
      nodeSelector:
        disk: "instance-store"
        karpenter.sh/capacity-type: spot
      containers:
        - name: data-archiver
          image: 270582689972.dkr.ecr.us-west-2.amazonaws.com/data-archiver:4a3958b
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          env:
            - name: AWS_REGION
              value: us-west-2
            - name: QUEUE_URL
              value: https://sqs.us-west-2.amazonaws.com/270582689972/data-archiver-queue
          resources:
            requests:
              cpu: "500m"
              memory: "1024Mi"
              ephemeral-storage: "8Gi"
            limits:
              cpu: "2000m"
              memory: "4096Mi"
              ephemeral-storage: "32Gi"
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 32Gi
